

public enum ReportType {
	STUDENT_PERFORMANCE,
	EXAM_TYPE_STUDENT_PERFORMANCE,
	TEACHER_PERFORMANCE,
	EXAM_TYPE_TEACHER_PERFORMANCE,
	GRADE_PERFORMANCE,
	EXAM_TYPE_GRADE_PERFORMANCE,
	GRADE_TEACHER_PERFORMANCE,
	EXAM_TYPE_GRADE_TEACHER_PERFORMANCE,
	EXIT;
}
